#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v3
# autospec commit: c1050fe
#
Name     : R-later
Version  : 1.3.2
Release  : 52
URL      : https://cran.r-project.org/src/contrib/later_1.3.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/later_1.3.2.tar.gz
Summary  : Utilities for Scheduling Functions to Execute Later with Event
Group    : Development/Tools
License  : MIT Zlib
Requires: R-later-lib = %{version}-%{release}
Requires: R-later-license = %{version}-%{release}
Requires: R-Rcpp
Requires: R-rlang
BuildRequires : R-Rcpp
BuildRequires : R-rlang
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
time, after the R execution stack has emptied. The functions are scheduled
    in an event loop.

%package lib
Summary: lib components for the R-later package.
Group: Libraries
Requires: R-later-license = %{version}-%{release}

%description lib
lib components for the R-later package.


%package license
Summary: license components for the R-later package.
Group: Default

%description license
license components for the R-later package.


%prep
%setup -q -n later
pushd ..
cp -a later buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1701910257

%install
export SOURCE_DATE_EPOCH=1701910257
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-later
cp %{_builddir}/later/LICENSE.note %{buildroot}/usr/share/package-licenses/R-later/1aec7d4290240555db0f8141162fb21c012930f7 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/later/DESCRIPTION
/usr/lib64/R/library/later/INDEX
/usr/lib64/R/library/later/LICENSE
/usr/lib64/R/library/later/Meta/Rd.rds
/usr/lib64/R/library/later/Meta/features.rds
/usr/lib64/R/library/later/Meta/hsearch.rds
/usr/lib64/R/library/later/Meta/links.rds
/usr/lib64/R/library/later/Meta/nsInfo.rds
/usr/lib64/R/library/later/Meta/package.rds
/usr/lib64/R/library/later/Meta/vignette.rds
/usr/lib64/R/library/later/NAMESPACE
/usr/lib64/R/library/later/NEWS.md
/usr/lib64/R/library/later/R/later
/usr/lib64/R/library/later/R/later.rdb
/usr/lib64/R/library/later/R/later.rdx
/usr/lib64/R/library/later/bgtest.cpp
/usr/lib64/R/library/later/doc/index.html
/usr/lib64/R/library/later/doc/later-cpp.Rmd
/usr/lib64/R/library/later/doc/later-cpp.html
/usr/lib64/R/library/later/help/AnIndex
/usr/lib64/R/library/later/help/aliases.rds
/usr/lib64/R/library/later/help/later.rdb
/usr/lib64/R/library/later/help/later.rdx
/usr/lib64/R/library/later/help/paths.rds
/usr/lib64/R/library/later/html/00Index.html
/usr/lib64/R/library/later/html/R.css
/usr/lib64/R/library/later/include/later.h
/usr/lib64/R/library/later/include/later_api.h
/usr/lib64/R/library/later/tests/testthat.R
/usr/lib64/R/library/later/tests/testthat/test-c-api.R
/usr/lib64/R/library/later/tests/testthat/test-cancel.R
/usr/lib64/R/library/later/tests/testthat/test-private-loops.R
/usr/lib64/R/library/later/tests/testthat/test-run_now.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/later/libs/later.so
/usr/lib64/R/library/later/libs/later.so.avx2
/usr/lib64/R/library/later/libs/later.so.avx512

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-later/1aec7d4290240555db0f8141162fb21c012930f7
